import 'package:get/get.dart';
class LocalString extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    'en_US': {
      "anasayfa": 'Home Screen',
      "ayarlar":"Settings",
      "temalar":"Themes",
      "beyaztema":"White Theme",
      "siyahtema":"Black Theme",
      "en": 'English',
      "tr": 'Turkish',
      "gemini": "Artificial Intelligence (Gemini)",
      "verebilirim": "How can I lose weight?",
      "diyetProgrol": "Create a Diet Program",
      "egzersizprogol": "Create an Exercise Program",
      "soruyazabilirsiniz": "You can write your questions here.",
      "merhabayardl": "Hello, can you help me?",
      "hakkimizda": "About Us",
      "bizeulas": "YOU CAN REACH US FROM THE LINKS BELOW",
      "profilduzenle": "Edit Profile",
      "dogumtarihi": "Date of Birth",
      "kullanici": "Username",
      "sifre": "Password",
      "benihatirla": "Remember Me",
      "girisyap": "Log In",
      "KayBulun": "Record Not Found!",
      "kayitol": "Sign Up",
      "besinler": "Foods",
      "alinan": "CONSUMED",
      "kcal": "KCAL",
      "yakilan": "BURNED",
      "karbonhidrat": "Carbohydrate",
      "protein": "Protein",
      "yag": "Fat",
      "bos": "Cannot Be Empty!",
      "tamam": "Okay",
      "sabah": "Breakfast",
      "ogle": "Lunch",
      "aksam": "Dinner",
      "guncellendi": "Successfully Updated!",
      "alanbos": "Fields Cannot Be Empty!",
      "bilgilerguncellendi": "Information Could Not Be Updated!",
      "guncelle": "Update",
      "isim": "Name",
      "soyisim": "Surname",
      "yas": "Age",
      "boy": "Height",
      "kilo": "Weight",
      "kullaniciyok": "Such User Already Exists!",
      "basarili": "You Signed Up Successfully!",
      "kayitol": "Sign Up",
      "zatenhesap": "Already Have an Account?",
      "giris": "Log In",
      "adimsayar": "Step Counter",
      "program": "Workout Start",
      "set": "Number of Sets",
      "antrenman": "Workout",
      "yuruyus": "WALK",
      "isinmaegzersiz": "WARM-UP EXERCISES",
      "tumvucutb": "FULL BODY BEGINNER LEVEL",
      "tumvucuto": "FULL BODY INTERMEDIATE LEVEL",
      "tumvucuti": "FULL BODY ADVANCED LEVEL",
      "planko": "PLANK INTERMEDIATE LEVEL",
      "karinb": "ABDOMINAL BEGINNER LEVEL",
      "tabatao": "TABATA INTERMEDIATE LEVEL",
      "tekrarorta": "QUICK REPETITION INTERMEDIATE LEVEL",
      "yanlarindanorta": "SIDE FAT BURNER INTERMEDIATE LEVEL",
      "cikis": "Log Out",
      "bugun": 'Today',
      "dun": 'Last Day',
      "onceki": 'Before Day',
      "erkek":'Man',
      "kadin":'Woman',
      "kullanicibuldr":'There is such a user!',

    },
    'tr_TR': {
      "anasayfa": 'Anasayfa',
      "ayarlar":"Ayarlar",
      "temalar":"Temalar",
      "beyaztema":"Beyaz Tema",
      "siyahtema":"Siyah Tema",
      "en": 'İngilizce',
      "tr": 'Türkçe',
      "gemini":"Yapay Zeka (Gemini)",
      "verebilirim":"Nasıl kilo verebilirim?",
      "diyetProgrol":"Diyet Programı oluştur.",
      "egzersizprogol":"Egzersiz programı oluştur.",
      "soruyazabilirsiniz":"Sorularınızı yazabilirsiniz?",
      "merhabayardl":"Merhaba yardımcı olur musunuz?",
      "hakkimizda":"Hakkımızda",
      "bizeulas":"BİZE AŞAĞIDAKİ LİNKLERDEN ULAŞABİLİRSİNİZ",
      "profilduzenle": 'Profil Düzenle',
      "dogumtarihi": 'Date of Birth',
      "kullanici": 'Kullanıcı Adı',
      "sifre": 'Şifre',
      "benihatirla": 'Beni Hatırla',
      "girisyap": 'Giriş Yap',
      "KayBulun": 'Kayıt Bulunamadı !',
      "kayitol": 'Kayıt Ol',
      "besinler": 'Besinler',
      "alinan": 'ALINAN',
      "kcal": 'KCAL',
      "yakilan": 'YAKILAN',
      "karbonhidrat": 'Karbonhidrat',
      "protein": 'Protein',
      "yag": 'Yağ',
      "bos": 'Boş Bırakılamaz!',
      "tamam": 'Tamam',
      "sabah": 'Sabah Kahvaltısı',
      "ogle": 'Öğle Yemeği',
      "aksam": 'Akşam Yemeği',
      "guncellendi": 'Başarıyla Güncellendi!',
      "alanbos": 'Alanlar Boş Bırakılamaz!',
      "bilgilerguncellendi": 'Bilgiler Güncellenemedi!',
      "guncelle": 'Güncelle',
      "isim": 'İsim',
      "soyisim": 'Soy ismi',
      "yas": 'Yaş',
      "boy": 'Boy',
      "kilo": 'Kilo',
      "kullaniciyok": 'Böyle Bir Kullanıcı Zaten Bulunmakta!',
      "basarili": 'Başarıyla Kaydoldunuz!',
      "kayitol": 'Kayıt Ol',
      "zatenhesap": 'Zaten Bir Hesabın Var Mı?',
      "giris": 'Giriş',
      "adimsayar": 'Adım Sayar',
      "program": 'Antreman Başlangıç',
      "set": 'Set Sayısı',
      "antrenman": 'Antrenman',
      "yuruyus": 'YÜRÜYÜŞ',
      "isinmaegzersiz": 'ISINMA EGZERSİZLERİ',
      "tumvucutb": 'TÜM VÜCUT BAŞLANGIÇ SEVİYE',
      "tumvucuto": 'TÜM VÜCUT ORTA SEVİYE',
      "tumvucuti": 'TÜM VÜCUT İLERİ SEVİYE',
      "planko": 'PLANK ORTA SEVİYE',
      "karinb": 'KARIN BAŞLANGIÇ SEVİYE',
      "tabatao": 'TABATA ORTA SEVİYE',
      "tekrarorta": 'HIZLI TEKRAR ORTA SEVİYE',
      "yanlarindanorta": 'YANLARDAN KURTULMA ORTA SEVİYE',
      "cikis": 'Çıkış Yap',
      "bugun": 'Bugün',
      "dun": 'Dün',
      "onceki": 'Önceki Gün',
      "erkek":'Erkek',
      "kadin":'Kadın',
      "kullanicibuldr":'Böyle Bir Kullanıcı Bulunmakta!',
    },

  };

}
